### ISSUE TITLE
Please don't show the output pane upon activation

### ISSUE THREAD

**Issue by gulshan** [zbecknell/asp-classic-support#19]
When this extension gets activated, it always opens up the output pane like this-
![image](https://user-images.githubusercontent.com/751732/197692067-b44fd6a0-cd47-4e42-9fa6-aa230ccf10fe.png)

I think this is caused by the code `output.show();` in this line-
https://github.com/zbecknell/asp-classic-support/blob/cf78ab7d5a86cf79e941e64f640632cd4c0a010b/src/extension.ts#L70

Can you please not show the output pane on activation? It is a bit distracting.

**Comment by zbecknell** [comment]
Thanks for pointing this out, I meant to remove it in the past but never got to it!
