### ISSUE TITLE
Setting Option for highlight background color for ASP

### ISSUE THREAD

**Issue by milacay** [zbecknell/asp-classic-support#8]
I started using your extension now and really like it.   
One Enhancement Request:
Currently, the code within the <% %> will be highlighted with background color.  Please give user the setting option to change it.

Thank you,

**Comment by zbecknell** [comment]
I have a new update that adds settings to disable or change the background colors. Search for ASP Classic in your settings to see them.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/9710256/117501187-b8a28a00-af4b-11eb-8a7c-b595863e5f16.png">

**Comment by milacay** [comment]
Wow. Thank you so much for the quick updates.  Great Work!
