### ISSUE TITLE
Style Intellisense not working after enabled this extension.

### ISSUE THREAD

**Issue by milacay** [zbecknell/asp-classic-support#9]
I think there is a bug.   When I enable this extension, the CSS Intelligense does not work for CSS inside the <style></style> 

Here is the screenshot of CSS works after disabled this extension:
![image](https://user-images.githubusercontent.com/12450039/117498505-bbdb4d00-af2e-11eb-84ce-dacf38f86ea8.png)

**Comment by zbecknell** [comment]
I'm working on fixing this now.  I need to let non-ASP sections pass through to be handled by the built-in HTML extension -- I've got it started but not quite ready yet.

**Comment by zbecknell** [comment]
This is fixed with 0.4.0.  Thanks for your help with addressing these issues!

**Comment by milacay** [comment]
Yes, I just tested it and it works correctly now.  Thanks again!
